# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01ac10d79658ca8770a68cbaa6b54389a16e763a68a6ab2e82003ccbe2c5d5fa921cbece39e22722ebb90b7172b1ed14fe9ee53408c8f297eca0a65e5d2d38a7

test:
  secret_key_base: 46245307b82504404a069c74b26363828c76ff115fca3d22ebf29b78e1efcadfa4f7d7533284ddbe1e3c2989af99203a0800c1f4fe117bd4f0ea2c32a4226758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
